framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation
        transports:
            kafka_events:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: enrollment.events
                    consumer_group: '%env(APP_ENV)%-enrollment-consumer'
        routing:
            'App\Enrollment\Domain\Event\UserEnrolled': kafka_events
