framework:
    messenger:
        default_bus: command.bus
        failure_transport: failed
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation
        transports:
            kafka_events:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: enrollment.events
                    consumer_group: '%env(APP_ENV)%-enrollment-consumer'
            kafka_progress:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: progress.events
                    consumer_group: '%env(APP_ENV)%-progress-producer'
            progress_enrollment_in:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: enrollment.events
                    consumer_group: '%env(APP_ENV)%-progress'
                retry_strategy: { max_retries: 3, delay: 1000, multiplier: 2 }
            notification_enrollment_in:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: enrollment.events
                    consumer_group: '%env(APP_ENV)%-notification'
                retry_strategy: { max_retries: 3, delay: 1000, multiplier: 2 }
            notification_progress_in:
                dsn: '%env(MESSENGER_KAFKA_EVENTS_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    topic: progress.events
                    consumer_group: '%env(APP_ENV)%-notification-progress'
                retry_strategy: { max_retries: 3, delay: 1000, multiplier: 2 }
            failed: 'doctrine://default?queue_name=failed'
        routing:
            'App\Enrollment\Domain\Event\UserEnrolled': kafka_events
            'App\Progress\Domain\Event\LessonCompleted': kafka_progress
            'App\Progress\Domain\Event\CourseCompleted': kafka_progress
