framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
        # Transporty (Kafka) dodaje Faza 4.
