# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

identity_controllers:
    resource:
        path: ../src/Identity/UI/Controller/
        namespace: App\Identity\UI\Controller
    type: attribute

catalog_controllers:
    resource:
        path: ../src/Catalog/UI/Controller/
        namespace: App\Catalog\UI\Controller
    type: attribute

enrollment_controllers:
    resource:
        path: ../src/Enrollment/UI/Controller/
        namespace: App\Enrollment\UI\Controller
    type: attribute

progress_controllers:
    resource:
        path: ../src/Progress/UI/Controller/
        namespace: App\Progress\UI\Controller
    type: attribute
